Moving changelog from readme to history
netuitive-community-packages/netuitive-packages-aws-ebs pull request #19
Opened 2019-03-01 21:41 UTC by rclagett

2019-03-01 22:18 UTC, codytipton approved these changes

2019-03-01 22:25 UTC, Grumblesmith requested changes

2019-03-01 22:25 UTC, Grumblesmith commented on HISTORY.md
> +
```suggestion
```
Please remove this whitespace.

2019-03-04 23:44 UTC, Grumblesmith approved these changes

2019-03-04 23:44 UTC, merged